# Generated by Django 4.2 on 2023-08-22 11:16

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Category',
            new_name='Tag',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='category',
        ),
        migrations.AddField(
            model_name='transaction',
            name='description',
            field=models.CharField(default='No Description', max_length=20),
        ),
        migrations.AddField(
            model_name='transaction',
            name='tag',
            field=models.ManyToManyField(blank=True, to='account.tag'),
        ),
    ]
